[Feature] handling orientation (v0.0.2)
PRNDcompany/GroundingDINO pull request #2
Opened 2023-05-19 04:58 UTC by justin-prnd

- remove unused batch prediction
- modify Boxes class to get xyxy as an input
- mp based server
- input orientation handling

2023-05-19 04:59 UTC, justin-prnd commented
docker: https://hub.docker.com/layers/prnd/gdino/v0.0.2/images/sha256-d6fc2f6402c48abb56f63f581d321697ab7a9f1d8ecafd076a0fc353f746a35f?context=repo

2023-05-31 06:48 UTC, evan-prnd approved these changes
추후 poetry 적용 및 prnd-utils 사용하면 좋을 것 같습니다.

2023-05-31 06:48 UTC, evan-prnd commented on groundingdino/deploy/server.py
> +            size = (None, None)
추후 `kserve.errors.InferenceError` raise 적용하면 좋을 것 같습니다.

2023-05-31 06:48 UTC, evan-prnd commented on groundingdino/deploy/server.py
> +        image_bytes = await input_.image.to_data(self.downloader)
추후 image_bytes가 none일 때 `kserve.errors.InvalidInput` raise 적용하면 좋을 것 같습니다.

2023-05-31 06:55 UTC, evan-prnd requested changes

2023-05-31 06:55 UTC, evan-prnd commented on groundingdino/deploy/server.py
> +    orientation: Optional[str] = None
다른 곳에서 `Optional` 처리가 보이지 않습니다. 따라서 아래 두 방법 중 하나로 처리가 필요해 보입니다.
1. 다른 곳에서 `Optional` 처리 로직 구현
2. `Optional[str] = None` -> `OrientationType = OrientationType.normal` 로 변경

2023-06-05 05:23 UTC, justin-prnd commented
리뷰 추후 반영

2023-06-05 05:23 UTC, merged